version: '3.8'
services:
  db:
    container_name: postgres
    image: jms-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${JMS_DATABASE_NAME}
      POSTGRES_USER: ${JMS_DATABASE_USER}
      POSTGRES_PASSWORD: ${JMS_DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

