version: '3.8'
services:
  db:
    container_name: postgres
    image: jms-db
    restart: always
    environment:
      POSTGRES_DB: ${JMS_DATABASE_NAME}
      POSTGRES_USER: ${JMS_DATABASE_USER}
      POSTGRES_PASSWORD: ${JMS_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
