ALTER TABLE public.resource
ALTER COLUMN price_per_quantity TYPE DECIMAL(10, 2),
ALTER COLUMN size TYPE DECIMAL(10, 2),
ALTER COLUMN carat TYPE DECIMAL(10, 2),
ALTER COLUMN dimensionx TYPE DECIMAL(10, 2),
ALTER COLUMN dimensiony TYPE DECIMAL(10, 2),
ALTER COLUMN dimensionz TYPE DECIMAL(10, 2);

ALTER TABLE public.resource_in_user
ALTER COLUMN quantity TYPE DECIMAL(10, 2);

ALTER TABLE public.resource_in_product
ALTER COLUMN quantity TYPE DECIMAL(10, 2);

ALTER TABLE public.product
ALTER COLUMN discount TYPE DECIMAL(10, 2),
ALTER COLUMN sale_price TYPE DECIMAL(10, 2);