version: 0.0
os: linux
files:
  - source: /docker/
    destination: /tmp/be
hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/check_health.sh
      timeout: 180
      runas: root