version: 0.2

run-as: root

env:
  secrets-manager:
    JMS_DATABASE_NAME: "JMS_DB_CREDS:JMS_DATABASE_NAME"
    JMS_DATABASE_USER: "JMS_DB_CREDS:JMS_DATABASE_USER"
    JMS_DATABASE_PASSWORD: "JMS_DB_CREDS:JMS_DATABASE_PASSWORD"
