ALTER TABLE public.resource
ADD COLUMN shape_specification VARCHAR(255) NULL,
ADD COLUMN color_hue VARCHAR(255) NULL,
ADD COLUMN polish VARCHAR(255) NULL,
ADD COLUMN symmetry VARCHAR(255) NULL,
ADD COLUMN fluorescence VARCHAR(255) NULL,
ADD COLUMN certificate VARCHAR(255) NULL,
ADD COLUMN treatment VARCHAR(255) NULL,
DROP COLUMN plating,
ALTER COLUMN size TYPE VARCHAR(255),
ALTER COLUMN carat TYPE NUMERIC(10,5);

ALTER TABLE allowed_value
ADD COLUMN sku VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE allowed_value
DROP CONSTRAINT allowed_value_pkey;

ALTER TABLE allowed_value
ADD CONSTRAINT allowed_value_pkey
PRIMARY KEY (resource_clazz, field_name, value, sku);

ALTER TABLE public.resource
ADD COLUMN sku VARCHAR(255) NOT NULL DEFAULT '';