package jewellery.inventory.model;

public enum EventType {
    RESOURCE_CHANGE,
    RESOURCEINUSER_TOPUP,
    RESOURCEINUSER_DELETION,
    RESOURCEINUSER_PRODUCT_TRANSFER,
    PRODUCT_DISASSEMBLY,
    SALE,
    USER_CREATION,
    USER_DELETION,
    ENTITY_UPDATE
}
