package jewellery.inventory.model;

public enum EventType {
  USER_CREATE,
  USER_UPDATE,
  USER_DELETE,
  RESOURCE_CREATE,
  RESOURCE_DELETE,
  RESOURCE_UPDATE,
  RESOURCE_TRANSFER,
  RESOURCE_QUANTITY_REMOVE,
  RESOURCE_IN_USER_TOP_UP,
  RESOURCE_IN_USER_DELETE,
  PRODUCT_CREATE,
  PRODUCT_TRANSFER,
  PRODUCT_DISASSEMBLY,
  SALE
}
