package jewellery.inventory.model;

public enum OrganizationPermission {
  DESTROY_ORGANIZATION,
  MANAGE_USERS,
  ADD_RESOURCE_QUANTITY,
  REMOVE_RESOURCE_QUANTITY,
  CREATE_PRODUCT,
  EDIT_PRODUCT,
  DISASSEMBLE_PRODUCT,
  TRANSFER_PRODUCT,
  CREATE_SALE,
  RETURN_RESOURCE,
  RETURN_PRODUCT,
  TRANSFER_RESOURCE
}
