# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and copy to S3

on:
  push:
    branches: [ "*" ]

permissions:
  id-token: write
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml

      - name: Copy jar to dockerfiles
        run: cp ./target/*.jar .github/dockerfiles/app.jar

      - name: Get shortened git hash
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build --file Dockerfile_jms_be -t vladokat/jms-be:$git_hash .
        working-directory: .github/dockerfiles/

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push vladokat/jms-be:$git_hash
